### PR TITLE
Controlled component support

### PR DESCRIPTION
**Pull request by madox2**
Allows to use segment control as a controlled react component

### CODE REVIEW

**Comment by kuraydev** [comment]
Hey @madox2 

It looks good to me :) I will test it today and will release it!

Thank you so much!

**Comment by tiste** [comment]
Hey @WrathChaos, is it something okay for you?

**Comment by tiste** [comment]
Hey @WrathChaos, is there any chance for this PR to be merged and released?
Thanks a lot.

**Comment by kuraydev** [comment]
Hello  @madox2 , @tiste 
Totally my bad. This PR completely lost through my list. 

I will test and merge today 🙏

**Comment by tiste** [comment]
@WrathChaos thanks a lot!

**Review by kuraydev — APPROVED** [review]
Awesome thank you so much! @madox2 
Again sorry for very late review

**Comment by kuraydev** [comment]
https://github.com/WrathChaos/react-native-segmented-control-2/releases/tag/2.0.1

Version 2 is released 🍻

**Comment by tiste** [comment]
@WrathChaos could you publish it to npm as well? Thanks again.

**Comment by kuraydev** [comment]
@tiste Published 🍻

**Pull request merged**
