### PR TITLE
Support RTL

### PR DESCRIPTION
**Pull request by b0iq**

### CODE REVIEW

**Review by kuraydev — APPROVED** [review]
Awesome contribution! 
@b0iq Thank you so much sir!

**Comment by kuraydev** [comment]
Hey @b0iq 
I am willing to release a new version but can you tell me how should I test the RTL support properly?

**Comment by b0iq** [comment]
> Hey @b0iq 
> 
> I am willing to release a new version but can you tell me how should I test the RTL support properly?


You can set the simulator to any RTL language for example Arabic "Ar" or by calling in top of App.js:
```
I18nManager.allowRTL(true);
I18nManager.forceRTL(true);
```
If doesn't work
Try to modify container view style to:
`style={{direction: 'rtl'}}` or if you are using flex use flex direction row-reverse 

[For more information](https://docs.expo.dev/guides/localization/)

**Comment by kuraydev** [comment]
[Version 1.1.0](https://github.com/WrathChaos/react-native-segmented-control-2/releases/tag/1.1.0) is released! 

Thank you so much for the contribution @b0iq!

**Pull request merged**
